### ISSUE TITLE
Images misdisplayed  in 0.3.0

### ISSUE THREAD

**Issue by Arrumaco** [citrus/spree_variant_options#11]
Hi again,

Playing in my demo site with the new 0.3.0 commit, I've found what is like to be a malfunction.  

When it goes to product/show after select a product in the index, it shows the buttons for the size and color variants (using the RoR BB jersey as demo), but below the main default picture, it adds all the images "thumbnails" for all variants and when you select an specific color, doesn't change the main image and still show all the thumbnails.

In another test, in Admin site, when I set the image for the different option_type it display the new partial to update the images files names, but in the show product of the store it uses that images to set the content of the variant button instead of leaving the name of the variant.

Please let me know if you need further information

I hope it helps!

**Comment by citrus** [comment]
This should be fixed on master @ 1f807b0
