### ISSUE TITLE
undefined method current=

### ISSUE THREAD

**Issue by ghost** [citrus/spree_variant_options#13]
Hi,

I don't know if this is my fault or not, but here goes:

I recently updated to spree 1-0-stable and update spree_variant_options

When going to the products show page, i get the following error:

NoMethodError: undefined method `current' for #<Class:0x000000054abdc0>
from activerecord-3.1.3/lib/active_record/base.rb:1088:in`method_missing'

When removing the unless defined? Spree::User::DestroyWithOrdersError block in lib/spree_variant_options.rb the page does work.

Sorry if this is something stupid I do.

**Comment by citrus** [comment]
Hmm I'll take a look. This may be an issue with spree_core since it relies on spree_auth to define the Spree::User::DestroyWithOrdersError class.. Let's see if the spree guys can shed some light on this.

\cc @spree @schof @BDQ @spree

**Comment by citrus** [comment]
Can you see if this is fixed when using master @ 37cec09? 

Thanks!

\ cc @sbounmy

**Comment by sbounmy** [comment]
fixed ;) thx !

**Comment by citrus** [comment]
No problem! Also, I released v0.4.0 which includes this fix..
