### ISSUE TITLE
Image-less version

### ISSUE THREAD

**Issue by greinacker** [citrus/spree_variant_options#15]
Any thoughts to refactoring this a bit so the image-related changes are optional?  I liked how this worked, but I didn't need the images, so I ended up creating a fork and stripping out the image-related code.  

It might be cool to have one gem that has the core variant-options functionality, and then perhaps another gem that adds on the image support.

Thoughts?  Happy to help if you think it's a good idea.

**Comment by citrus** [comment]
The images for option values are optional so you should be able to just leave them blank right?

**Comment by greinacker** [comment]
Yes, leaving them blank works fine...I was looking to avoid having to
make an unnecessary database change.

On Feb 28, 2012, at 6:36 PM, Spencer Steffen
reply@reply.github.com
wrote:

**Comment by citrus** [comment]
Gotcha. So far I've found my clients like the image option so my vote is that stays. Cool?

**Comment by greinacker** [comment]
Fair enough! :)

On Feb 28, 2012, at 6:44 PM, Spencer Steffen
reply@reply.github.com
wrote:

**Comment by citrus** [comment]
Right on, cheers!
