### ISSUE TITLE
unused option values

### ISSUE THREAD

**Issue by sbounmy** [citrus/spree_variant_options#16]
Hi,

The extension is working great so far, except I have the following scenario :

Option Type : 
- size (M L XL)
- color (blue, black, red, green, purple, brown, grey, white)

Let's say I create a product with the following :
- option types : size and color.
- variants : M-blue, L-blue, XL-blue, M-red, L-red, XL-red.

In this case, on my product page, I only want to display the option values 'blue' and 'red', since I can only have 2 distinct choice for the color.

The other way would be to create specific set of 'colors' but I would endup with a lot of option_types...

Any idea ?

Thanks,
Stephane

**Comment by citrus** [comment]
To fix this we'd have to rewrite the `option_values` method inside the product decorator to only find option values that are linked to the product's variants. If I have some time later tonight I'll try a couple solutions...

**Comment by sbounmy** [comment]
Thx citrus! I will try something by myself too, let me know if you got something.

**Comment by citrus** [comment]
How about this?

``` ruby
  def option_values
    #option_types.map{|i| i.option_values }.flatten.uniq
    Spree::OptionValue.where(:id => variants.map(&:option_value_ids).flatten.uniq)
  end
```

It's untested but I think it would work..

**Comment by citrus** [comment]
Or even better?

``` ruby
def option_values
  variants.map(&:option_values).flatten.uniq
end
```

**Comment by citrus** [comment]
I just pushed 165ff90 that should fix this :)

**Comment by sbounmy** [comment]
@citrus Awesome !!!

My option types are sorted in a different order, but I am fine with that.
Thanks!!

**Comment by citrus** [comment]
You're welcome! Let me see if I can get them to sort properly too :)
