### ISSUE TITLE
Price display when product is out of stock

### ISSUE THREAD

**Issue by sbounmy** [citrus/spree_variant_options#18]
hi citrus,

I encountered the following scenario : a product is totally out of stock (variants's hand_on = 0), there is no way to display the price of the product.

Here is a screenshot :
![screenshot](http://i42.tinypic.com/w7bjvn.png)

Maybe we should default to the master variant somehow, so we can display the price and let the customer add to the wishlist aswell :)

I will try to investigate further.

Let me know what you think,

Stephane

**Comment by citrus** [comment]
Good find! I like the idea of defaulting to the master variant when all other variants are out of stock..

**Comment by citrus** [comment]
This was fixed in #19 right?

**Comment by sbounmy** [comment]
Yes it is! forgot to close, my bad !

**Comment by citrus** [comment]
No worries :)
