### ISSUE TITLE
Consider registering assets for precompilation?

### ISSUE THREAD

**Issue by nhunzaker** [citrus/spree_variant_options#22]
I've been having some issues on Heroku (where assets must be precompiled). Here's what I did to get it to work:

https://gist.github.com/2022542

Any thoughts?

**Comment by citrus** [comment]
You shouldn't have to do this if you're already including the assets in your manifest file. For example, in `app/assets/stylesheets/store/all.css` you should have something like this:

``` css
/*
 *= require store/variant_options
 *= require_self
 *= require_tree . 
*/
```

And in `app/assets/javascripts/store/all.js`

``` js
//= require store/spree_core
//= require store/product_variant_options
//= require store/variant_options
```

I just pushed fc2079a241 which adds a manifest files for spree_variant_options. This way you can add spree_variant_options to your application like this:

``` css
/*
 *= require spree_variant_options
 *= require_self
 *= require_tree . 
*/
```

``` js
//= require store/spree_core
//= require spree_variant_options
```

Let me know if you have any questions!

**Comment by nhunzaker** [comment]
Fair enough, haha.
