### ISSUE TITLE
Add to Cart never enabled if not tracking inventory

### ISSUE THREAD

**Issue by greinacker** [citrus/spree_variant_options#24]
I have a project which does not track inventory, via

```
Spree.config do |config|
  # [...]
  config.track_inventory_levels = false
end
```

Commit 015ca6ce8f27f4a63437bd7424136d02b04cf587 from @sbounmy breaks my store, in that the "Add to Cart" button is never enabled.  Specifically, this line:

```
      if (variant.count > 0)
        $('#cart-form button[type=submit]').attr('disabled', false).fadeTo(100, 1);
```

My count is always 0, so the button never gets enabled. :-(

I've reverted back to commit d2d9a2b8b556d18a869c375b975876880b394c00 for now, but would be nice to fix this for master.

I would have fixed it myself, but I'm not entirely sure what all is going on in that javascript code for inventory tracking, so I didn't want to break it!

**Comment by citrus** [comment]
Thanks for the report Greg. 

The fix might be as simple as adding a check for `allow_select_outofstock` in  that line of js.. @sbounmy would probably know best.

Here's what I'm thinking but this could be way wrong....

``` js
if (variant.count > 0 || allow_select_outofstock)
  $('#cart-form button[type=submit]').attr('disabled', false).fadeTo(100, 1);
```

Thoughts?

-Spencer

**Comment by sbounmy** [comment]
Hi @greinacker,

First of all sorry for the regression, I don't remember precisely why I did variant.count > 0, but I guess I totally forgot about track_inventory_levels config option.

I will add a test and fix this asap.

I noticed there are 2 different options track_inventory_levels and allow_backorders, do you guys know the difference ?

@citrus looks like I might have broken cucumber specs, I will also try to fix that and if you have any idea why it is broken let me know ^^

Stephane.

**Comment by sbounmy** [comment]
@citrus I think I will add a track_inventory_levels param to the js constructor, so if this is true, we will automatically enable the button.

**Comment by citrus** [comment]
Stephane, 

I'm pretty sure the track_inventory_levels option manages the inventory count while the allow_backorders option is for allowing a product to be purchased when the inventory count is 0. So the latter won't matter without the prior...

Thanks for looking into this!

-Spencer

**Comment by citrus** [comment]
Sounds like a good solution! The only regression that I could think of there is that an invalid combination of option types and values could result in a variant that doesn't exist... Thoughts?

**Comment by greinacker** [comment]
Agree there - seems like a simple solution might be something like

```
if (variant.count > 0 || track_inventory_levels)
```

**Comment by sbounmy** [comment]
hey @greinacker,

could you please try https://github.com/sbounmy/spree_variant_options/tree/fix_config_track_inventory_levels

My test just hang up when setting track_inventory_levels to false, so I could'nt really test correctly.

Stephane

**Comment by greinacker** [comment]
Working on this...I'm actually having trouble reproducing the problem at the moment, so trying to get back to where I found it...

**Comment by greinacker** [comment]
@sbounmy on your version, I'm getting:

```
TypeError: 'undefined' is not an object (evaluating 'options[key[0]][key[1]]')
```

in the inventory function:

``` javascript
  function inventory(btns) {
    var keys, variants, count = 0, selected = {};
    var sels = $.map(divs.find('a.selected'), function(i) { return i.rel });
    $.each(sels, function(key, value) {
      key = value.split('-');
      var v = options[key[0]][key[1]];
all.js:10092TypeError: 'undefined' is not an object (evaluating 'options[key[0]][key[1]]')
      keys = $.keys(v);
      var m = Array.find_matches(selection.concat(keys));
      if (selection.length == 0) {
        selection = keys;
```

(showing error inline in the above)

**Comment by sbounmy** [comment]
it should work now, I've tested using the dummy app  and test is passing : https://github.com/sbounmy/spree_variant_options/tree/fix_config_track_inventory_levels

**Comment by greinacker** [comment]
Working for me!  Nice work - thanks.

**Comment by citrus** [comment]
This is resolved, right?

**Comment by sbounmy** [comment]
I think so, I fixed this with my recent PR.

**Comment by citrus** [comment]
Awesome :) Thanks Stephane.
