### ISSUE TITLE
Failing Scenario: Should show variant images when a selection is made

### ISSUE THREAD

**Issue by rbrown** [citrus/spree_variant_options#6]
This scenario fails for me at "I should see "Small Green" in the variant images label" unless I copy the contents of public into test/dummy/public

I don't know if that's because dummier is doing something wrong, or the test suite is or I am. This is with rails-3.0.9 spree 0.60.2 and ruby 1.9.2

**Comment by citrus** [comment]
fixed in d3b7bf95c6acab77d117
