### ISSUE TITLE
Options with Images Link Broken

### ISSUE THREAD

**Issue by dhawalshah** [citrus/spree_variant_options#8]
For images associated with the options, the link is broken for Spree 0.70.3. It shows all the variant option images.

**Comment by citrus** [comment]
spree_variant_options is not compatible with 0.70.x yet.. sorry!

**Comment by citrus** [comment]
I just pushed the 0.70.x commits.. try installing spree_variant_options like so:

```
gem "spree_variant_options", :git => "git://github.com/citrus/spree_variant_options.git", :branch => "master"
```

Thanks!
